#!/bin/sh

# This script uses grep to search test cases generated by
# create-test-cases-from-generated-expressions.py in which clc produces the
# wrong answer (due to binary representation; default) or correct but truncated
# answer (if -t option is given).
#
# Syntax: [-t] test-case-file

_answers_to_show="wrong only"
[ "$1" = "-t" ] && _answers_to_show="wrong and truncated" && shift

_test_case_file=$1

[ "$_answers_to_show" = "wrong only" ] && egrep -B 2 ^#.+assert "$_test_case_file"
[ "$_answers_to_show" = "wrong and truncated" ] && egrep -B 1 -A 1 ^# "$_test_case_file"
